### ISSUE TITLE
Cannot Import into JCB version 2.10.9

### ISSUE THREAD

**Issue by philecom** [vdm-io/Joomla-Members-Manager#2]
I'm trying to import this component into JCB version 2.10.9 but I keep on getting this error.

"Data is corrupt!
This could be due to key error, or broken package!
Import error."

I'm sure it has to do with the key. I will be glad if you can supply the encryption key.

**Comment by Llewellynvdm** [comment]
https://vdm.bz/how-to-get-free-vdm-package-keys
